#!/usr/bin/env python3
"""
sync_specs.py — ONE source for the agent specs, generated wrappers for every platform.

Source of truth (edit these, nothing else):
  .agents/skills/<stage>/SKILL.md     the fetcher / ranker skill bodies (cross-agent convention)
  .claude/agents/<name>.md            the four role specs (Claude subagent format)
  .claude/commands/<cmd>.md           the slash commands / orchestrator

Generated (never edit by hand — `python3 tools/sync_specs.py` rewrites them):
  .claude/skills/<stage>/SKILL.md     copy of .agents/skills (Claude Code reads this path)
  .codex/agents/<name>.toml           Codex agent = same body, TOML-wrapped
  .codex/skills/<skill>/SKILL.md      Codex skill = same command body (agents/openai.yaml is kept)
  .agent/workflows/<cmd>.md           Antigravity workflow = same command body
  .agent/rules/pipeline.md            Antigravity rule pointing at AGENTS.md / DAILY_RUN.md

`--check` exits 1 if any generated file is stale (runs from tools/check.sh), so the three
platforms cannot drift again.
"""
from __future__ import annotations
import sys, shutil, filecmp
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BANNER = "GENERATED by tools/sync_specs.py from {src} — edit the source, then run `python3 tools/sync_specs.py`."
COMMAND_TO_SKILL = {"apply-run": "apply-run", "fetch": "job-fetch", "rank": "job-rank",
                    "find-contacts": "job-contacts", "customise": "resume-customise", "interview": "interview-prep"}
WORKFLOWS = ["apply-run", "fetch", "rank", "customise", "find-contacts", "interview"]


def frontmatter(text: str) -> tuple[dict, str]:
    """Tiny YAML-ish front matter reader: scalars and `key: >` folded blocks."""
    if not text.startswith("---\n"):
        return {}, text
    head, _, body = text[4:].partition("\n---\n")
    meta, key = {}, None
    for line in head.splitlines():
        if line.startswith((" ", "\t")) and key:
            meta[key] = (meta[key] + " " + line.strip()).strip()
        elif ":" in line:
            key, _, val = line.partition(":")
            key, val = key.strip(), val.strip()
            meta[key] = "" if val == ">" else val
    return meta, body


def toml_str(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def render() -> dict[Path, str | Path]:
    out: dict[Path, str | Path] = {}
    # 1. .agents/skills → .claude/skills and .codex/skills (byte copies)
    for src in (ROOT / ".agents" / "skills").glob("*/SKILL.md"):
        out[ROOT / ".claude" / "skills" / src.parent.name / "SKILL.md"] = src
        out[ROOT / ".codex" / "skills" / src.parent.name / "SKILL.md"] = src
    # 2. .claude/agents/*.md → .codex/agents/*.toml
    for src in sorted((ROOT / ".claude" / "agents").glob("*.md")):
        meta, body = frontmatter(src.read_text(encoding="utf-8"))
        name = meta.get("name", src.stem)
        toml = (f"# {BANNER.format(src=src.relative_to(ROOT))}\n"
                f"name = {toml_str(name)}\n"
                f"description = {toml_str(meta.get('description', ''))}\n"
                f"developer_instructions = '''\n{body.strip()}\n'''\n")
        out[ROOT / ".codex" / "agents" / f"{name}.toml"] = toml
    # 3. .claude/commands/*.md → .codex/skills/<skill>/SKILL.md and .agent/workflows/<cmd>.md
    for cmd, skill in COMMAND_TO_SKILL.items():
        src = ROOT / ".claude" / "commands" / f"{cmd}.md"
        if not src.exists():
            continue
        meta, body = frontmatter(src.read_text(encoding="utf-8"))
        desc = meta.get("description", "")
        note = (f"<!-- {BANNER.format(src=src.relative_to(ROOT))} -->\n"
                "In this tool, \"delegate to the <name> subagent\" means: open `.claude/agents/<name>.md` "
                "(same text as `.codex/agents/<name>.toml`) and carry out that role inline, one stage at a time. "
                "`$ARGUMENTS` is whatever the user typed after the command.\n\n")
        out[ROOT / ".codex" / "skills" / skill / "SKILL.md"] = f"---\nname: {skill}\ndescription: {desc}\n---\n{note}{body.strip()}\n"
        if cmd in WORKFLOWS:
            out[ROOT / ".agent" / "workflows" / f"{cmd}.md"] = f"---\ndescription: {desc}\n---\n{note}{body.strip()}\n"
    out[ROOT / ".agent" / "rules" / "pipeline.md"] = (
        f"<!-- {BANNER.format(src='.claude/commands + AGENTS.md')} -->\n"
        "---\ntrigger: always_on\n---\n"
        "This workspace is the job-application pipeline. Read `AGENTS.md` first, then `DAILY_RUN.md` — they are the "
        "authoritative sequence and guardrails. Run stages one at a time, never in parallel, and stop at Gate A and "
        "Gate B. Never apply to a job or send a message: the candidate does every submission. Supabase is the record "
        "for applications and the seen-job ledger; the tracker (`job_tracker.html`) reads it live, nothing deploys it. "
        "Workflows: `/apply-run`, `/fetch`, `/rank`, `/customise`, `/find-contacts`, `/interview`.\n")
    return out


def main(check: bool) -> int:
    stale = []
    for dst, content in render().items():
        if isinstance(content, Path):
            same = dst.exists() and filecmp.cmp(content, dst, shallow=False)
        else:
            same = dst.exists() and dst.read_text(encoding="utf-8") == content
        if same:
            continue
        stale.append(dst)
        if not check:
            dst.parent.mkdir(parents=True, exist_ok=True)
            if isinstance(content, Path):
                shutil.copyfile(content, dst)
            else:
                dst.write_text(content, encoding="utf-8")
    if check:
        for p in stale:
            print(f"STALE: {p.relative_to(ROOT)}  (run python3 tools/sync_specs.py)")
        print("sync_specs: all generated specs current" if not stale else f"sync_specs: {len(stale)} stale")
        return 1 if stale else 0
    for p in stale:
        print(f"wrote {p.relative_to(ROOT)}")
    print(f"sync_specs: {len(stale)} file(s) regenerated" if stale else "sync_specs: nothing to do")
    return 0


if __name__ == "__main__":
    sys.exit(main("--check" in sys.argv))
